@startuml PetClinic UseCase

skinparam actorStyle awesome

left to right direction


:Vet: --> (Utworzenie godzin przyjęć)
:Vet: --> (Dokonanie rejestracji)
:Vet: --> (Modyfikacja terminu wizyty)
:Vet: --> (Logowanie)
' owner - usecases
:Owner: --> (Dodanie zwierzaka do systemu)
:Owner: --> (Umówienie wizyty)
' :Owner: --> (Wybór terminu wizyty)
:Owner: --> (Usunięcie wizyty)
:Owner: --> (Dokonanie rejestracji)
:Owner: --> (Logowanie)

(Dokonanie rejestracji) -> (Logowanie) #line.dashed : <extends>

(Wybór terminu wizyty) <- (Wybór zwierzaka) #line.dashed : <extends>
(Usunięcie wizyty) -> (Wybór terminu wizyty) #line.dashed : <include>
(Wybór zwierzaka) <- (Umówienie wizyty) #line.dashed : <extends>
(Modyfikacja terminu wizyty) -> (Anulowanie wizyty) #line.dashed : <includes>

@enduml