@startuml PetClinic


abstract Human{
    -String firstName
    -String surname
}

entity Owner extends Human {
    -Long ownerId
    +void addNewPet(Pet)
    +void addNewVisit(Pet)
    +void cancelVisit(Long id)
    +Pet getPetById(Long)
}

entity Vet extends Human {
    -Long vetId
    -List<Visit> visits
    -Date workingHours
}

entity Visit {
    -Long visitId
    -Date beginTime
    -Long petId
}

entity Pet {
    -Long petId
    -String name
    -String species
    -List<Visit> visits
}


interface VetRepository 
interface PetRepository 
interface OwnerRepository
interface VisitRepository
interface JpaRepository

JpaRepository <|.. VetRepository
JpaRepository <|.. PetRepository
OwnerRepository ..|> JpaRepository
VisitRepository ..|> JpaRepository

PetRepository <|.. PetService
VetRepository <|.. VetService
OwnerService ..|> OwnerRepository
VisitService ..|> VisitRepository

class OwnerService {
    -OwnerRepository ownerRepository
    -VisitRepository visitRepository
    -PetRepository petRepository
    +Owner findOwner(Long)
    +Owner updateOwner(Owner, Long)
    +void deleteOwner(Long)
    +Pet addPet(Owner, Pet)
    +List findAllOwners()
}

class PetService {
    -PetRepository repository
    +List findAllPets()
    +Pet createPet(String, String)
    +void deletePet()
}

class VetService {
    -VetRepository repository
    +List findAllVets()
    +Vet findVet(Long)
    +Vet updateVet(Vet, Long)
    +void deleteVet(Long)
}

class VisitService {
    -VisitRepository repository
    +Visit createVisit(Pet)
    +void deleteVisit()
    +List<Visit> getAllVisits()
    +Visit getVisitById()
}

class GreetingController {

}

class OwnerController {
    -OwnerService ownerService
    +List getAllOwners()
    +Owner getOwner(@PathVariable Long)
    +Owner updateOwner(Owner, Long)
    +void delete(Long)
    +Pet getPet(Long, Long)
}

class PetController {

}

class VetController {
    -VetService vetService
    -VisitService visitService
    +List<Vet> getAllVets()
    +Vet getVet(@PathVariable Long)
    +Vet updateVet(@RequestBody Vet, @PathVariable Long)
    +void deleteVet(@PathVariable Long)
}

class VisitController {

}

@enduml