@startuml PetClinic Sequence1 Create Account

actor User
participant LoginService
participant VetRepository
participant OwnerRepository

User -> LoginService : registration(credentials, roleKey)

loop
    LoginService -> VetRepository : searchForAccount(username)
end

alt roleKey == vet
    alt invalid data type given
        LoginService -> User : UserNotCreatedException()
    end
    VetRepository -> LoginService : returnVet()
    alt account already exists
        User <- LoginService : AccountAlreadyExistException(username)
    end
    LoginService -> VetRepository : createAccount(credentials)
    
end

loop
    LoginService -> OwnerRepository : searchForAccount(username)
end

alt roleKey == owner
    alt invalid data type given
        LoginService -> User : UserNotCreatedException()
    end
    OwnerRepository -> LoginService : returnOwner()
    alt account already exists
        User <- LoginService : AccountAlreadyExistException(username)
    end
    LoginService -> OwnerRepository : createAccount(credentials)
    
end

LoginService -> User : invalidRoleKeyException()

@enduml