@startuml Sequence2 Make An Appointment

actor Owner
participant OwnerService

participant PetService
participant PetRepository

participant VisitService
participant VisitRepository


OwnerService -> PetService : getAllPets()

loop
    PetService -> PetRepository : searchForPetsByOwner(id)
end

PetRepository -> PetService : returnPets()

alt no pets
    OwnerService -> Owner : backToOwnerManagement()
end

note right
w sytuacji braku zwierząt 
nie można umówić wizyty
end note

Owner -> OwnerService : choosePet(Pet)
OwnerService -> PetService : getPet(id)

OwnerService -> VisitService : createVisit(Pet, Visit)

note over VisitRepository
nie można wybrać 
uprzednio zajętego terminu
end note
alt visit already booked
    OwnerService -> Owner : backToOwnerManagement()
end

VisitService -> VisitRepository : bookVisit(Visit, Pet)
OwnerService -> Owner : backToOwnerManagement()

@enduml